export const TOPICS = [
  { id: 'healthcare', en: 'Healthcare & Medicine', ar: 'الرعاية الصحية والطب' },
  { id: 'education', en: 'Education & EdTech', ar: 'التعليم وتكنولوجيا التعليم' },
  { id: 'environment', en: 'Environment & Sustainability', ar: 'البيئة والاستدامة' },
  { id: 'finance', en: 'Finance & FinTech', ar: 'المالية والتكنولوجيا المالية' },
  { id: 'ecommerce', en: 'E-commerce & Retail', ar: 'التجارة الإلكترونية والتجزئة' },
  { id: 'agriculture', en: 'Agriculture & AgriTech', ar: 'الزراعة والتكنولوجيا الزراعية' },
  { id: 'transportation', en: 'Transportation & Logistics', ar: 'النقل والخدمات اللوجستية' },
  { id: 'smart_cities', en: 'Smart Cities', ar: 'المدن الذكية' },
  { id: 'cybersecurity', en: 'Cybersecurity', ar: 'الأمن السيبراني' },
  { id: 'entertainment', en: 'Entertainment & Media', ar: 'الترفيه والإعلام' },
  { id: 'accessibility', en: 'Accessibility', ar: 'إمكانية الوصول (ذوي الهمم)' },
  { id: 'tourism', en: 'Tourism & Hospitality', ar: 'السياحة والضيافة' },
  { id: 'manufacturing', en: 'Manufacturing & Industry 4.0', ar: 'التصنيع والصناعة 4.0' },
  { id: 'energy', en: 'Energy & Utilities', ar: 'الطاقة والمرافق' },
  { id: 'space', en: 'Space Technology', ar: 'تكنولوجيا الفضاء' },
  { id: 'robotics', en: 'Robotics & Automation', ar: 'الروبوتات والأتمتة' },
  { id: 'social_good', en: 'Social Good & Non-Profit', ar: 'النفع العام والمؤسسات غير الربحية' },
  { id: 'sports', en: 'Sports & Fitness', ar: 'الرياضة واللياقة البدنية' },
  { id: 'real_estate', en: 'Real Estate & PropTech', ar: 'العقارات وتكنولوجيا العقارات' },
  { id: 'legal', en: 'Legal & RegTech', ar: 'القانون والتكنولوجيا التنظيمية' },
  { id: 'gaming', en: 'Gaming & eSports', ar: 'الألعاب والرياضات الإلكترونية' },
  { id: 'art', en: 'Art & Design', ar: 'الفن والتصميم' },
  { id: 'music', en: 'Music & Audio', ar: 'الموسيقى والصوتيات' },
  { id: 'hr', en: 'Human Resources', ar: 'الموارد البشرية' },
  { id: 'food', en: 'Food & Beverage', ar: 'الأغذية والمشروبات' },
  { id: 'construction', en: 'Construction Tech', ar: 'تكنولوجيا البناء' },
  { id: 'biotech', en: 'Biotechnology', ar: 'التكنولوجيا الحيوية' },
  { id: 'blockchain', en: 'Blockchain & Web3', ar: 'البلوكتشين والويب 3' },
  { id: 'ar_vr', en: 'AR/VR & Metaverse', ar: 'الواقع المعزز/الافتراضي والميتافيرس' },
  { id: 'iot', en: 'Internet of Things (IoT)', ar: 'إنترنت الأشياء' },
];
