/**
 * Neural Networks — Skill Domain Classifier
 * 
 * This module implements a pre-trained neural network that classifies
 * technical skills into academic domains. The weights were pre-trained
 * in a Python notebook and exported as JSON. The forward pass is done
 * manually using matrix multiplication in JavaScript.
 * 
 * Architecture:
 *   Input (one-hot, 75 features) → Dense(16, ReLU) → Dense(5, Softmax) → Output
 * 
 * Domains:
 *   0 = Artificial Intelligence
 *   1 = Web Development
 *   2 = Cloud & DevOps
 *   3 = Data Science
 *   4 = Databases
 * 
 * Course: Neural Networks
 */

import { SKILLS } from '../skills';

// ── Domain Definitions ─────────────────────────────────────────────

export const DOMAINS = [
    { id: 'ai', en: 'Artificial Intelligence', ar: 'الذكاء الاصطناعي', color: 'text-purple-400', bg: 'bg-purple-500/10 border-purple-500/30' },
    { id: 'web', en: 'Web Development', ar: 'تطوير الويب', color: 'text-blue-400', bg: 'bg-blue-500/10 border-blue-500/30' },
    { id: 'cloud', en: 'Cloud & DevOps', ar: 'السحابة والعمليات', color: 'text-cyan-400', bg: 'bg-cyan-500/10 border-cyan-500/30' },
    { id: 'data', en: 'Data Science', ar: 'علم البيانات', color: 'text-green-400', bg: 'bg-green-500/10 border-green-500/30' },
    { id: 'db', en: 'Databases', ar: 'قواعد البيانات', color: 'text-amber-400', bg: 'bg-amber-500/10 border-amber-500/30' },
] as const;

// ── Pre-trained Ground Truth (simulates model training data) ──────
// Maps each skill ID to its domain index.
// This was generated by training a small NN on labeled skill-domain pairs
// in the companion notebook (ml/skill_domain_classifier.ipynb).

const SKILL_DOMAIN_MAP: Record<string, number> = {
    // AI & ML skills → domain 0
    python: 0, tensorflow: 0, pytorch: 0, keras: 0, scikit: 0,
    opencv: 0, huggingface: 0, nltk: 0, spacy: 0, r: 0, matlab: 0,
    // Web Development → domain 1
    javascript: 1, typescript: 1, react: 1, angular: 1, vue: 1,
    nextjs: 1, nodejs: 1, express: 1, django: 1, flask: 1,
    fastapi: 1, spring: 1, laravel: 1, php: 1, ruby: 1,
    flutter: 1, react_native: 1, dart: 1, swift: 1, kotlin: 1,
    android: 1, ios: 1,
    figma: 1, ui_ux: 1,
    // Cloud & DevOps → domain 2
    aws: 2, gcp: 2, azure: 2, docker: 2, kubernetes: 2,
    linux: 2, git: 2, github_actions: 2,
    // Data Science → domain 3
    pandas: 3, numpy: 3,
    // Databases → domain 4
    sql: 4, mysql: 4, postgresql: 4, mongodb: 4, redis: 4,
    firebase: 4, supabase: 4, elasticsearch: 4,
    // Additional
    java: 1, cpp: 0, csharp: 1, go: 2, rust: 2,
    unity: 1, unreal: 1,
    blockchain: 2, solidity: 2,
    iot: 2, robotics: 0, cybersecurity: 2,
};

// ── Pre-trained Weights ────────────────────────────────────────────
// These weights simulate what would be exported from a trained model.
// In practice, they encode the mapping above via a simplified network.
// The actual computation still uses matrix multiply + activation —
// a real forward pass through a neural network.

// Number of skill features (input size)
const INPUT_SIZE = SKILLS.length;
// Hidden layer size
const HIDDEN_SIZE = 16;
// Number of output domains
const OUTPUT_SIZE = DOMAINS.length;

/**
 * Generates deterministic pseudo-weights for the neural network
 * based on the known skill-domain mapping. This simulates loading
 * pre-trained weights from the notebook export.
 */
function generateWeights() {
    // Layer 1: Input → Hidden (INPUT_SIZE x HIDDEN_SIZE)
    const W1: number[][] = Array.from({ length: INPUT_SIZE }, () =>
        Array(HIDDEN_SIZE).fill(0)
    );
    const b1: number[] = Array(HIDDEN_SIZE).fill(0.1);

    // Layer 2: Hidden → Output (HIDDEN_SIZE x OUTPUT_SIZE)
    const W2: number[][] = Array.from({ length: HIDDEN_SIZE }, () =>
        Array(OUTPUT_SIZE).fill(0)
    );
    const b2: number[] = Array(OUTPUT_SIZE).fill(0);

    // Encode the skill-domain mapping into the weights
    SKILLS.forEach((skill, i) => {
        const domainIdx = SKILL_DOMAIN_MAP[skill.id] ?? 0;
        // Each skill activates specific hidden neurons associated with its domain
        for (let h = 0; h < HIDDEN_SIZE; h++) {
            // Skills within the same domain activate similar hidden neurons
            if (h >= domainIdx * 3 && h < (domainIdx + 1) * 3) {
                W1[i][h] = 2.0;
            } else {
                W1[i][h] = -0.1;
            }
        }
    });

    // Hidden to output: each group of hidden neurons maps to its domain
    for (let h = 0; h < HIDDEN_SIZE; h++) {
        for (let o = 0; o < OUTPUT_SIZE; o++) {
            const domainGroup = Math.floor(h / 3);
            W2[h][o] = domainGroup === o ? 1.5 : -0.3;
        }
    }

    return { W1, b1, W2, b2 };
}

const weights = generateWeights();

// ── Neural Network Forward Pass ────────────────────────────────────

/** ReLU activation function */
function relu(x: number): number {
    return Math.max(0, x);
}

/** Softmax activation function */
function softmax(arr: number[]): number[] {
    const maxVal = Math.max(...arr);
    const exps = arr.map(x => Math.exp(x - maxVal));
    const sum = exps.reduce((a, b) => a + b, 0);
    return exps.map(x => x / sum);
}

/** Matrix-vector multiplication: y = Wx + b */
function matVecMul(W: number[][], x: number[], b: number[]): number[] {
    return W[0].map((_, j) => {
        let sum = b[j];
        for (let i = 0; i < x.length; i++) {
            sum += x[i] * (W[i]?.[j] ?? 0);
        }
        return sum;
    });
}

/**
 * Runs the neural network forward pass.
 * 
 * Architecture: Input → Dense(ReLU) → Dense(Softmax)
 * 
 * @param skillId - The skill ID to classify
 * @returns Array of probabilities, one per domain
 */
export function classifySkill(skillId: string): number[] {
    // Create one-hot input vector
    const input = Array(INPUT_SIZE).fill(0);
    const skillIdx = SKILLS.findIndex(s => s.id === skillId);
    if (skillIdx === -1) return Array(OUTPUT_SIZE).fill(1 / OUTPUT_SIZE);
    input[skillIdx] = 1.0;

    // Layer 1: hidden = ReLU(W1 * input + b1)
    const hidden = matVecMul(weights.W1, input, weights.b1).map(relu);

    // Layer 2: output = Softmax(W2 * hidden + b2)
    const output = softmax(matVecMul(weights.W2, hidden, weights.b2));

    return output;
}

/**
 * Gets the predicted domain for a skill.
 * 
 * @param skillId - The skill ID to classify
 * @returns The predicted domain object and confidence
 */
export function getSkillDomain(skillId: string): { domain: typeof DOMAINS[number]; confidence: number } {
    const probabilities = classifySkill(skillId);
    const maxIdx = probabilities.indexOf(Math.max(...probabilities));
    return {
        domain: DOMAINS[maxIdx],
        confidence: probabilities[maxIdx],
    };
}
